"""initial migration

Revision ID: 15888ccb60c7
Revises: 30606c9413
Create Date: 2015-08-13 16:05:13.029596

"""

# revision identifiers, used by Alembic.
revision = '15888ccb60c7'
down_revision = '30606c9413'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'disabled')
    op.drop_column('albums', 'disabled')
    ### end Alembic commands ###
