"""initial migration

Revision ID: 1e97f8d9edc1
Revises: 32dac99d243b
Create Date: 2015-07-24 17:32:23.416306

"""

# revision identifiers, used by Alembic.
revision = '1e97f8d9edc1'
down_revision = '32dac99d243b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'avatar_hash')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
