"""initial migration

Revision ID: 32dac99d243b
Revises: 14d90443ed4b
Create Date: 2015-07-24 16:15:02.022223

"""

# revision identifiers, used by Alembic.
revision = '32dac99d243b'
down_revision = '14d90443ed4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
