"""initial migration

Revision ID: 4b4613c58fb3
Revises: 94f9dbef336
Create Date: 2015-09-17 18:26:18.941648

"""

# revision identifiers, used by Alembic.
revision = '4b4613c58fb3'
down_revision = '94f9dbef336'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    ### end Alembic commands ###
