"""initial migration

Revision ID: 94f9dbef336
Revises: 1e0e6598fa56
Create Date: 2015-08-31 17:45:19.766324

"""

# revision identifiers, used by Alembic.
revision = '94f9dbef336'
down_revision = '1e0e6598fa56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'title')
    ### end Alembic commands ###
